# Site settings
title: Malav Bhavsar
description: 'Senior Software Engineer at Square. I lead high-impact cross-organizational projects and engineering teams. Interested in Distributed Systems, Fintech, Blockchain and Machine Learning.'
url: 'http://malav.io'
baseurl: '/'
google_analytics: 'UA-72841310-1'

author:
  name: 'Malav Bhavsar'
  email: 'malav.bhavsar@gmail.com'
  twitter_username: malavbhavsar
  github_username:  malavbhavsar
  linkedin_username:  malavbhavsar

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-responsive-image

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

responsive_image:
  # Path to the image template.
  template: _includes/responsive-image.html
  default_quality: 100
  sizes:
    - width: 256
    - width: 340
    - width: 600
    - width: 640

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
